### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by zwischenloesung** [inofix/maestro.py#13]
Hi hugurp and Veit,

is it ok for you to switch the license of this project from GPLv3 to a double-license of both GPLv3 and MIT, or do you have any objections?

Thanks for your "official" feedback here.

Cheers,
mic

**Comment by hellerve** [comment]
Hey, thanks for asking!

I’m quite alright with relicensing the project; I actually think it’s a great move if you want to attract collaborators!

Cheers

**Comment by 4www** [comment]
Same here, thanks and go!

**Comment by zwischenloesung** [comment]
Thank you guys!
